from app import app
from model import db, Book, BookImage

# Comprehensive collection of 100 books across all genres
sample_books = [
    # Classic Literature & Fiction
    {
        'title': 'The Great Gatsby',
        'author': 'F. Scott Fitzgerald',
        'isbn': '978-0-7432-7356-5',
        'publisher': 'Scribner',
        'publication_year': 1925,
        'pages': 180,
        'language': 'English',
        'genre': 'Fiction',
        'format': 'Paperback',
        'price': 12.99,
        'stock': 25,
        'description': 'A classic American novel set in the Jazz Age, exploring themes of wealth, love, idealism, and moral decay.',
        'delivery_date': 3
    },
    {
        'title': 'To Kill a Mockingbird',
        'author': 'Harper Lee',
        'isbn': '978-0-06-112008-4',
        'publisher': 'J.B. Lippincott & Co.',
        'publication_year': 1960,
        'pages': 376,
        'language': 'English',
        'genre': 'Fiction',
        'format': 'Hardcover',
        'price': 18.50,
        'stock': 30,
        'description': 'A gripping tale of racial injustice and childhood innocence in the American South.',
        'delivery_date': 2
    },
    {
        'title': 'The Catcher in the Rye',
        'author': 'J.D. Salinger',
        'isbn': '978-0-316-76948-0',
        'publisher': 'Little, Brown and Company',
        'publication_year': 1951,
        'pages': 277,
        'language': 'English',
        'genre': 'Fiction',
        'format': 'Hardcover',
        'price': 16.99,
        'stock': 15,
        'description': 'A coming-of-age story following teenager Holden Caulfield in New York City.',
        'delivery_date': 3
    },
    {
        'title': 'One Hundred Years of Solitude',
        'author': 'Gabriel García Márquez',
        'isbn': '978-0-06-088328-7',
        'publisher': 'Harper & Row',
        'publication_year': 1967,
        'pages': 417,
        'language': 'English',
        'genre': 'Fiction',
        'format': 'Paperback',
        'price': 15.99,
        'stock': 22,
        'description': 'A masterpiece of magical realism chronicling the Buendía family through seven generations.',
        'delivery_date': 3
    },
    {
        'title': 'Moby Dick',
        'author': 'Herman Melville',
        'isbn': '978-0-14-243724-7',
        'publisher': 'Penguin Classics',
        'publication_year': 1851,
        'pages': 635,
        'language': 'English',
        'genre': 'Fiction',
        'format': 'Paperback',
        'price': 14.99,
        'stock': 18,
        'description': 'The epic tale of Captain Ahab\'s obsessive quest for the white whale.',
        'delivery_date': 4
    },
    {
        'title': 'The Lord of the Rings: The Fellowship of the Ring',
        'author': 'J.R.R. Tolkien',
        'isbn': '978-0-547-92822-7',
        'publisher': 'Houghton Mifflin Harcourt',
        'publication_year': 1954,
        'pages': 481,
        'language': 'English',
        'genre': 'Fantasy',
        'format': 'Paperback',
        'price': 17.99,
        'stock': 35,
        'description': 'The beginning of the epic fantasy journey through Middle-earth.',
        'delivery_date': 3
    },
    {
        'title': 'Jane Eyre',
        'author': 'Charlotte Brontë',
        'isbn': '978-0-14-144114-6',
        'publisher': 'Penguin Classics',
        'publication_year': 1847,
        'pages': 507,
        'language': 'English',
        'genre': 'Fiction',
        'format': 'Paperback',
        'price': 13.99,
        'stock': 20,
        'description': 'A powerful story of an orphaned girl who becomes a governess and finds love and independence.',
        'delivery_date': 3
    },
    {
        'title': 'The Brothers Karamazov',
        'author': 'Fyodor Dostoevsky',
        'isbn': '978-0-374-52797-9',
        'publisher': 'Farrar, Straus and Giroux',
        'publication_year': 1880,
        'pages': 796,
        'language': 'English',
        'genre': 'Fiction',
        'format': 'Hardcover',
        'price': 24.99,
        'stock': 12,
        'description': 'A philosophical novel about faith, doubt, and morality through the story of a Russian family.',
        'delivery_date': 5
    },
    {
        'title': 'Wuthering Heights',
        'author': 'Emily Brontë',
        'isbn': '978-0-14-143955-6',
        'publisher': 'Penguin Classics',
        'publication_year': 1847,
        'pages': 366,
        'language': 'English',
        'genre': 'Fiction',
        'format': 'Paperback',
        'price': 12.99,
        'stock': 25,
        'description': 'A dark tale of passion and revenge set on the Yorkshire moors.',
        'delivery_date': 3
    },
    {
        'title': 'The Odyssey',
        'author': 'Homer',
        'isbn': '978-0-14-044911-2',
        'publisher': 'Penguin Classics',
        'publication_year': -800,
        'pages': 541,
        'language': 'English',
        'genre': 'Fiction',
        'format': 'Paperback',
        'price': 15.99,
        'stock': 28,
        'description': 'The epic journey of Odysseus as he attempts to return home after the Trojan War.',
        'delivery_date': 4
    },
    
    # Science Fiction
    {
        'title': '1984',
        'author': 'George Orwell',
        'isbn': '978-0-452-28423-4',
        'publisher': 'Signet Classics',
        'publication_year': 1949,
        'pages': 328,
        'language': 'English',
        'genre': 'Science Fiction',
        'format': 'Paperback',
        'price': 13.95,
        'stock': 40,
        'description': 'A dystopian social science fiction novel about totalitarian control and surveillance.',
        'delivery_date': 3
    },
    {
        'title': 'Dune',
        'author': 'Frank Herbert',
        'isbn': '978-0-441-17271-9',
        'publisher': 'Ace Books',
        'publication_year': 1965,
        'pages': 688,
        'language': 'English',
        'genre': 'Science Fiction',
        'format': 'Paperback',
        'price': 16.00,
        'stock': 35,
        'description': 'An epic science fiction novel set on the desert planet Arrakis.',
        'delivery_date': 5
    },
    {
        'title': 'Foundation',
        'author': 'Isaac Asimov',
        'isbn': '978-0-553-29335-0',
        'publisher': 'Bantam Spectra',
        'publication_year': 1951,
        'pages': 244,
        'language': 'English',
        'genre': 'Science Fiction',
        'format': 'Paperback',
        'price': 14.99,
        'stock': 30,
        'description': 'The first novel in Asimov\'s Foundation series about psychohistory and the fall of the Galactic Empire.',
        'delivery_date': 3
    },
    {
        'title': 'Brave New World',
        'author': 'Aldous Huxley',
        'isbn': '978-0-06-085052-4',
        'publisher': 'Harper Perennial Modern Classics',
        'publication_year': 1932,
        'pages': 268,
        'language': 'English',
        'genre': 'Science Fiction',
        'format': 'Paperback',
        'price': 15.99,
        'stock': 32,
        'description': 'A dystopian novel about a technologically advanced society that has eliminated suffering.',
        'delivery_date': 3
    },
    {
        'title': 'Fahrenheit 451',
        'author': 'Ray Bradbury',
        'isbn': '978-1-4516-7331-9',
        'publisher': 'Simon & Schuster',
        'publication_year': 1953,
        'pages': 249,
        'language': 'English',
        'genre': 'Science Fiction',
        'format': 'Paperback',
        'price': 13.99,
        'stock': 28,
        'description': 'A dystopian novel about a future society where books are banned and burned.',
        'delivery_date': 3
    },
    {
        'title': 'The Martian',
        'author': 'Andy Weir',
        'isbn': '978-0-553-41802-6',
        'publisher': 'Crown',
        'publication_year': 2011,
        'pages': 369,
        'language': 'English',
        'genre': 'Science Fiction',
        'format': 'Paperback',
        'price': 16.99,
        'stock': 45,
        'description': 'A survival story about an astronaut stranded on Mars who must use science to survive.',
        'delivery_date': 2
    },
    {
        'title': 'Neuromancer',
        'author': 'William Gibson',
        'isbn': '978-0-441-56956-9',
        'publisher': 'Ace Books',
        'publication_year': 1984,
        'pages': 271,
        'language': 'English',
        'genre': 'Science Fiction',
        'format': 'Paperback',
        'price': 15.99,
        'stock': 25,
        'description': 'A cyberpunk novel that coined the term \'cyberspace\' and defined the genre.',
        'delivery_date': 3
    },
    {
        'title': 'Ender\'s Game',
        'author': 'Orson Scott Card',
        'isbn': '978-0-8125-5070-2',
        'publisher': 'Tor Books',
        'publication_year': 1985,
        'pages': 324,
        'language': 'English',
        'genre': 'Science Fiction',
        'format': 'Paperback',
        'price': 14.99,
        'stock': 38,
        'description': 'A military science fiction novel about a young boy trained to fight an alien invasion.',
        'delivery_date': 3
    },
    {
        'title': 'The Hitchhiker\'s Guide to the Galaxy',
        'author': 'Douglas Adams',
        'isbn': '978-0-345-39180-3',
        'publisher': 'Del Rey',
        'publication_year': 1979,
        'pages': 224,
        'language': 'English',
        'genre': 'Science Fiction',
        'format': 'Paperback',
        'price': 13.99,
        'stock': 42,
        'description': 'A comedic science fiction series that begins with the destruction of Earth.',
        'delivery_date': 2
    },
    {
        'title': 'Blade Runner (Do Androids Dream of Electric Sheep?)',
        'author': 'Philip K. Dick',
        'isbn': '978-0-345-40447-6',
        'publisher': 'Del Rey',
        'publication_year': 1968,
        'pages': 244,
        'language': 'English',
        'genre': 'Science Fiction',
        'format': 'Paperback',
        'price': 14.99,
        'stock': 30,
        'description': 'A story about synthetic humans and what it means to be human in a post-apocalyptic world.',
        'delivery_date': 3
    },
    
    # Fantasy
    {
        'title': 'Harry Potter and the Philosopher\'s Stone',
        'author': 'J.K. Rowling',
        'isbn': '978-0-7475-3269-9',
        'publisher': 'Bloomsbury',
        'publication_year': 1997,
        'pages': 223,
        'language': 'English',
        'genre': 'Fantasy',
        'format': 'Paperback',
        'price': 12.99,
        'stock': 50,
        'description': 'The first book in the beloved series about a young wizard\'s adventures at Hogwarts.',
        'delivery_date': 2
    },
    {
        'title': 'The Hobbit',
        'author': 'J.R.R. Tolkien',
        'isbn': '978-0-547-92822-8',
        'publisher': 'Houghton Mifflin Harcourt',
        'publication_year': 1937,
        'pages': 310,
        'language': 'English',
        'genre': 'Fantasy',
        'format': 'Paperback',
        'price': 14.99,
        'stock': 40,
        'description': 'The adventure of Bilbo Baggins as he joins a quest to reclaim the dwarf kingdom.',
        'delivery_date': 3
    },
    {
        'title': 'A Game of Thrones',
        'author': 'George R.R. Martin',
        'isbn': '978-0-553-10354-0',
        'publisher': 'Bantam Spectra',
        'publication_year': 1996,
        'pages': 694,
        'language': 'English',
        'genre': 'Fantasy',
        'format': 'Paperback',
        'price': 18.99,
        'stock': 35,
        'description': 'The first book in A Song of Ice and Fire series, full of political intrigue and fantasy elements.',
        'delivery_date': 4
    },
    {
        'title': 'The Name of the Wind',
        'author': 'Patrick Rothfuss',
        'isbn': '978-0-7564-0474-1',
        'publisher': 'DAW Books',
        'publication_year': 2007,
        'pages': 662,
        'language': 'English',
        'genre': 'Fantasy',
        'format': 'Paperback',
        'price': 17.99,
        'stock': 28,
        'description': 'The first book in The Kingkiller Chronicle about Kvothe, a legendary figure.',
        'delivery_date': 4
    },
    {
        'title': 'The Way of Kings',
        'author': 'Brandon Sanderson',
        'isbn': '978-0-7653-2635-5',
        'publisher': 'Tor Books',
        'publication_year': 2010,
        'pages': 1007,
        'language': 'English',
        'genre': 'Fantasy',
        'format': 'Hardcover',
        'price': 27.99,
        'stock': 20,
        'description': 'The first book in The Stormlight Archive, an epic fantasy with unique magic systems.',
        'delivery_date': 5
    },
    {
        'title': 'The Lion, the Witch and the Wardrobe',
        'author': 'C.S. Lewis',
        'isbn': '978-0-06-023481-4',
        'publisher': 'HarperCollins',
        'publication_year': 1950,
        'pages': 206,
        'language': 'English',
        'genre': 'Fantasy',
        'format': 'Paperback',
        'price': 11.99,
        'stock': 32,
        'description': 'Four children discover a magical world through a wardrobe in this classic fantasy.',
        'delivery_date': 3
    },
    
    # Romance
    {
        'title': 'Pride and Prejudice',
        'author': 'Jane Austen',
        'isbn': '978-0-14-143951-8',
        'publisher': 'Penguin Classics',
        'publication_year': 1813,
        'pages': 432,
        'language': 'English',
        'genre': 'Romance',
        'format': 'Paperback',
        'price': 11.99,
        'stock': 20,
        'description': 'A romantic novel about manners, marriage, and society in Georgian England.',
        'delivery_date': 4
    },
    {
        'title': 'Sense and Sensibility',
        'author': 'Jane Austen',
        'isbn': '978-0-14-143966-2',
        'publisher': 'Penguin Classics',
        'publication_year': 1811,
        'pages': 409,
        'language': 'English',
        'genre': 'Romance',
        'format': 'Paperback',
        'price': 12.99,
        'stock': 18,
        'description': 'A tale of two sisters with contrasting temperaments navigating love and society.',
        'delivery_date': 3
    },
    {
        'title': 'Outlander',
        'author': 'Diana Gabaldon',
        'isbn': '978-0-440-21256-8',
        'publisher': 'Dell',
        'publication_year': 1991,
        'pages': 896,
        'language': 'English',
        'genre': 'Romance',
        'format': 'Paperback',
        'price': 19.99,
        'stock': 25,
        'description': 'A time-traveling romance set between 20th century and 18th century Scotland.',
        'delivery_date': 4
    },
    {
        'title': 'The Notebook',
        'author': 'Nicholas Sparks',
        'isbn': '978-0-446-60523-3',
        'publisher': 'Grand Central Publishing',
        'publication_year': 1996,
        'pages': 214,
        'language': 'English',
        'genre': 'Romance',
        'format': 'Paperback',
        'price': 13.99,
        'stock': 30,
        'description': 'A touching love story about a couple\'s enduring romance through the decades.',
        'delivery_date': 2
    },
    {
        'title': 'Me Before You',
        'author': 'Jojo Moyes',
        'isbn': '978-0-14-312454-1',
        'publisher': 'Penguin Books',
        'publication_year': 2012,
        'pages': 369,
        'language': 'English',
        'genre': 'Romance',
        'format': 'Paperback',
        'price': 15.99,
        'stock': 35,
        'description': 'A heart-wrenching story about a caregiver and her quadriplegic employer.',
        'delivery_date': 3
    },
    
    # Mystery & Thriller
    {
        'title': 'The Girl with the Dragon Tattoo',
        'author': 'Stieg Larsson',
        'isbn': '978-0-307-45454-1',
        'publisher': 'Vintage Crime/Black Lizard',
        'publication_year': 2005,
        'pages': 672,
        'language': 'English',
        'genre': 'Mystery',
        'format': 'Paperback',
        'price': 16.99,
        'stock': 28,
        'description': 'A journalist and a hacker investigate a wealthy family\'s dark secrets.',
        'delivery_date': 3
    },
    {
        'title': 'Gone Girl',
        'author': 'Gillian Flynn',
        'isbn': '978-0-307-58836-4',
        'publisher': 'Crown Publishers',
        'publication_year': 2012,
        'pages': 419,
        'language': 'English',
        'genre': 'Thriller',
        'format': 'Paperback',
        'price': 15.99,
        'stock': 32,
        'description': 'A psychological thriller about a marriage gone terribly wrong.',
        'delivery_date': 2
    },
    {
        'title': 'The Da Vinci Code',
        'author': 'Dan Brown',
        'isbn': '978-0-307-47928-5',
        'publisher': 'Anchor',
        'publication_year': 2003,
        'pages': 689,
        'language': 'English',
        'genre': 'Thriller',
        'format': 'Paperback',
        'price': 17.99,
        'stock': 40,
        'description': 'A symbologist uncovers a conspiracy involving the Catholic Church and the Holy Grail.',
        'delivery_date': 3
    },
    {
        'title': 'And Then There Were None',
        'author': 'Agatha Christie',
        'isbn': '978-0-06-207348-4',
        'publisher': 'William Morrow Paperbacks',
        'publication_year': 1939,
        'pages': 264,
        'language': 'English',
        'genre': 'Mystery',
        'format': 'Paperback',
        'price': 14.99,
        'stock': 35,
        'description': 'Ten strangers are invited to an island where they begin dying one by one.',
        'delivery_date': 3
    },
    {
        'title': 'The Silent Patient',
        'author': 'Alex Michaelides',
        'isbn': '978-1-250-30170-7',
        'publisher': 'Celadon Books',
        'publication_year': 2019,
        'pages': 336,
        'language': 'English',
        'genre': 'Thriller',
        'format': 'Hardcover',
        'price': 18.99,
        'stock': 25,
        'description': 'A psychotherapist becomes obsessed with treating a woman who refuses to speak.',
        'delivery_date': 2
    },
    {
        'title': 'The Murder of Roger Ackroyd',
        'author': 'Agatha Christie',
        'isbn': '978-0-06-207349-1',
        'publisher': 'William Morrow Paperbacks',
        'publication_year': 1926,
        'pages': 312,
        'language': 'English',
        'genre': 'Mystery',
        'format': 'Paperback',
        'price': 13.99,
        'stock': 30,
        'description': 'Hercule Poirot investigates the murder of Roger Ackroyd in this classic mystery.',
        'delivery_date': 3
    },
    
    # Non-Fiction
    {
        'title': 'Sapiens: A Brief History of Humankind',
        'author': 'Yuval Noah Harari',
        'isbn': '978-0-06-231609-7',
        'publisher': 'Harper',
        'publication_year': 2014,
        'pages': 443,
        'language': 'English',
        'genre': 'Non-Fiction',
        'format': 'Paperback',
        'price': 16.99,
        'stock': 40,
        'description': 'A thought-provoking exploration of human history and our impact on the world.',
        'delivery_date': 3
    },
    {
        'title': 'Educated',
        'author': 'Tara Westover',
        'isbn': '978-0-399-59050-4',
        'publisher': 'Random House',
        'publication_year': 2018,
        'pages': 334,
        'language': 'English',
        'genre': 'Biography',
        'format': 'Hardcover',
        'price': 19.99,
        'stock': 35,
        'description': 'A memoir about education, family, and the struggle between loyalty and independence.',
        'delivery_date': 2
    },
    {
        'title': 'The Immortal Life of Henrietta Lacks',
        'author': 'Rebecca Skloot',
        'isbn': '978-1-4000-5217-2',
        'publisher': 'Crown Publishers',
        'publication_year': 2010,
        'pages': 381,
        'language': 'English',
        'genre': 'Non-Fiction',
        'format': 'Paperback',
        'price': 15.99,
        'stock': 28,
        'description': 'The story of how one woman\'s cells revolutionized medical science.',
        'delivery_date': 3
    },
    {
        'title': 'Becoming',
        'author': 'Michelle Obama',
        'isbn': '978-1-5247-6313-8',
        'publisher': 'Crown',
        'publication_year': 2018,
        'pages': 448,
        'language': 'English',
        'genre': 'Biography',
        'format': 'Hardcover',
        'price': 21.99,
        'stock': 45,
        'description': 'The memoir of former First Lady Michelle Obama.',
        'delivery_date': 2
    },
    {
        'title': 'Atomic Habits',
        'author': 'James Clear',
        'isbn': '978-0-7352-1129-2',
        'publisher': 'Avery',
        'publication_year': 2018,
        'pages': 320,
        'language': 'English',
        'genre': 'Self-Help',
        'format': 'Paperback',
        'price': 17.99,
        'stock': 50,
        'description': 'A guide to building good habits and breaking bad ones through small changes.',
        'delivery_date': 2
    },
    
    # Historical Fiction
    {
        'title': 'The Book Thief',
        'author': 'Markus Zusak',
        'isbn': '978-0-375-84220-7',
        'publisher': 'Knopf Books for Young Readers',
        'publication_year': 2005,
        'pages': 552,
        'language': 'English',
        'genre': 'Historical Fiction',
        'format': 'Paperback',
        'price': 16.99,
        'stock': 30,
        'description': 'A story about a young girl living in Nazi Germany who steals books.',
        'delivery_date': 3
    },
    {
        'title': 'All Quiet on the Western Front',
        'author': 'Erich Maria Remarque',
        'isbn': '978-0-449-21394-3',
        'publisher': 'Fawcett',
        'publication_year': 1929,
        'pages': 295,
        'language': 'English',
        'genre': 'Historical Fiction',
        'format': 'Paperback',
        'price': 14.99,
        'stock': 25,
        'description': 'A powerful anti-war novel about German soldiers in World War I.',
        'delivery_date': 3
    },
    {
        'title': 'The Pillars of the Earth',
        'author': 'Ken Follett',
        'isbn': '978-0-451-16689-4',
        'publisher': 'New American Library',
        'publication_year': 1989,
        'pages': 973,
        'language': 'English',
        'genre': 'Historical Fiction',
        'format': 'Paperback',
        'price': 19.99,
        'stock': 22,
        'description': 'An epic tale of the building of a cathedral in 12th-century England.',
        'delivery_date': 5
    },
    {
        'title': 'Cold Mountain',
        'author': 'Charles Frazier',
        'isbn': '978-0-8021-3540-9',
        'publisher': 'Grove Press',
        'publication_year': 1997,
        'pages': 449,
        'language': 'English',
        'genre': 'Historical Fiction',
        'format': 'Paperback',
        'price': 16.99,
        'stock': 20,
        'description': 'A Confederate soldier\'s journey home to his beloved during the Civil War.',
        'delivery_date': 4
    },
    
    # Horror
    {
        'title': 'The Shining',
        'author': 'Stephen King',
        'isbn': '978-0-307-74365-7',
        'publisher': 'Anchor',
        'publication_year': 1977,
        'pages': 659,
        'language': 'English',
        'genre': 'Horror',
        'format': 'Paperback',
        'price': 16.99,
        'stock': 35,
        'description': 'A family becomes caretakers of an isolated hotel that has a violent past.',
        'delivery_date': 3
    },
    {
        'title': 'Dracula',
        'author': 'Bram Stoker',
        'isbn': '978-0-14-143984-6',
        'publisher': 'Penguin Classics',
        'publication_year': 1897,
        'pages': 418,
        'language': 'English',
        'genre': 'Horror',
        'format': 'Paperback',
        'price': 13.99,
        'stock': 30,
        'description': 'The classic vampire novel that defined the genre.',
        'delivery_date': 3
    },
    {
        'title': 'Frankenstein',
        'author': 'Mary Shelley',
        'isbn': '978-0-14-143947-1',
        'publisher': 'Penguin Classics',
        'publication_year': 1818,
        'pages': 280,
        'language': 'English',
        'genre': 'Horror',
        'format': 'Paperback',
        'price': 12.99,
        'stock': 28,
        'description': 'The story of Victor Frankenstein and his creation, exploring themes of science and humanity.',
        'delivery_date': 3
    },
    {
        'title': 'It',
        'author': 'Stephen King',
        'isbn': '978-1-5011-4243-0',
        'publisher': 'Scribner',
        'publication_year': 1986,
        'pages': 1138,
        'language': 'English',
        'genre': 'Horror',
        'format': 'Paperback',
        'price': 20.99,
        'stock': 25,
        'description': 'A group of children face an ancient evil that feeds on fear in the town of Derry.',
        'delivery_date': 5
    },
    
    # Young Adult
    {
        'title': 'The Hunger Games',
        'author': 'Suzanne Collins',
        'isbn': '978-0-439-02348-1',
        'publisher': 'Scholastic Press',
        'publication_year': 2008,
        'pages': 374,
        'language': 'English',
        'genre': 'Young Adult',
        'format': 'Paperback',
        'price': 14.99,
        'stock': 40,
        'description': 'A dystopian story about a televised fight to the death among teenagers.',
        'delivery_date': 2
    },
    {
        'title': 'The Fault in Our Stars',
        'author': 'John Green',
        'isbn': '978-0-14-242417-9',
        'publisher': 'Penguin Books',
        'publication_year': 2012,
        'pages': 313,
        'language': 'English',
        'genre': 'Young Adult',
        'format': 'Paperback',
        'price': 13.99,
        'stock': 35,
        'description': 'A love story between two teenagers who meet in a cancer support group.',
        'delivery_date': 2
    },
    {
        'title': 'Divergent',
        'author': 'Veronica Roth',
        'isbn': '978-0-06-202402-2',
        'publisher': 'Katherine Tegen Books',
        'publication_year': 2011,
        'pages': 487,
        'language': 'English',
        'genre': 'Young Adult',
        'format': 'Paperback',
        'price': 15.99,
        'stock': 30,
        'description': 'In a dystopian Chicago, society is divided into five factions based on virtues.',
        'delivery_date': 3
    },
    {
        'title': 'The Perks of Being a Wallflower',
        'author': 'Stephen Chbosky',
        'isbn': '978-1-4516-9621-9',
        'publisher': 'MTV Books',
        'publication_year': 1999,
        'pages': 213,
        'language': 'English',
        'genre': 'Young Adult',
        'format': 'Paperback',
        'price': 12.99,
        'stock': 32,
        'description': 'A coming-of-age story told through letters from an introverted teenager.',
        'delivery_date': 2
    },
    
    # Philosophy & Religion
    {
        'title': 'Meditations',
        'author': 'Marcus Aurelius',
        'isbn': '978-0-14-044933-4',
        'publisher': 'Penguin Classics',
        'publication_year': 180,
        'pages': 304,
        'language': 'English',
        'genre': 'Philosophy',
        'format': 'Paperback',
        'price': 13.99,
        'stock': 25,
        'description': 'Personal reflections of the Roman Emperor on Stoic philosophy.',
        'delivery_date': 3
    },
    {
        'title': 'The Republic',
        'author': 'Plato',
        'isbn': '978-0-14-044914-3',
        'publisher': 'Penguin Classics',
        'publication_year': -380,
        'pages': 405,
        'language': 'English',
        'genre': 'Philosophy',
        'format': 'Paperback',
        'price': 15.99,
        'stock': 20,
        'description': 'Plato\'s influential dialogue on justice, the ideal state, and the nature of reality.',
        'delivery_date': 4
    },
    {
        'title': 'Man\'s Search for Meaning',
        'author': 'Viktor E. Frankl',
        'isbn': '978-0-8070-1427-1',
        'publisher': 'Beacon Press',
        'publication_year': 1946,
        'pages': 165,
        'language': 'English',
        'genre': 'Philosophy',
        'format': 'Paperback',
        'price': 14.99,
        'stock': 35,
        'description': 'A Holocaust survivor\'s reflection on finding meaning in the most difficult circumstances.',
        'delivery_date': 3
    },
    
    # Business & Economics
    {
        'title': 'Think and Grow Rich',
        'author': 'Napoleon Hill',
        'isbn': '978-1-58542-433-7',
        'publisher': 'Sound Wisdom',
        'publication_year': 1937,
        'pages': 320,
        'language': 'English',
        'genre': 'Business',
        'format': 'Paperback',
        'price': 16.99,
        'stock': 30,
        'description': 'A classic self-help book on achieving personal and financial success.',
        'delivery_date': 3
    },
    {
        'title': 'The Lean Startup',
        'author': 'Eric Ries',
        'isbn': '978-0-307-88789-4',
        'publisher': 'Crown Business',
        'publication_year': 2011,
        'pages': 336,
        'language': 'English',
        'genre': 'Business',
        'format': 'Paperback',
        'price': 18.99,
        'stock': 25,
        'description': 'A guide to building successful startups through validated learning and innovation.',
        'delivery_date': 3
    },
    {
        'title': 'Good to Great',
        'author': 'Jim Collins',
        'isbn': '978-0-06-662099-2',
        'publisher': 'HarperBusiness',
        'publication_year': 2001,
        'pages': 320,
        'language': 'English',
        'genre': 'Business',
        'format': 'Paperback',
        'price': 17.99,
        'stock': 28,
        'description': 'Research-based insights on what makes companies transition from good to great.',
        'delivery_date': 3
    },
    
    # Science & Technology
    {
        'title': 'A Brief History of Time',
        'author': 'Stephen Hawking',
        'isbn': '978-0-553-38016-3',
        'publisher': 'Bantam',
        'publication_year': 1988,
        'pages': 256,
        'language': 'English',
        'genre': 'Science',
        'format': 'Paperback',
        'price': 15.99,
        'stock': 30,
        'description': 'An accessible explanation of cosmology and theoretical physics.',
        'delivery_date': 3
    },
    {
        'title': 'The Selfish Gene',
        'author': 'Richard Dawkins',
        'isbn': '978-0-19-929114-4',
        'publisher': 'Oxford University Press',
        'publication_year': 1976,
        'pages': 360,
        'language': 'English',
        'genre': 'Science',
        'format': 'Paperback',
        'price': 16.99,
        'stock': 25,
        'description': 'A revolutionary look at evolution from the gene\'s perspective.',
        'delivery_date': 3
    },
    {
        'title': 'The Code Breaker',
        'author': 'Walter Isaacson',
        'isbn': '978-1-9821-1585-2',
        'publisher': 'Simon & Schuster',
        'publication_year': 2021,
        'pages': 560,
        'language': 'English',
        'genre': 'Science',
        'format': 'Hardcover',
        'price': 24.99,
        'stock': 20,
        'description': 'The biography of Jennifer Doudna and the story of CRISPR gene editing.',
        'delivery_date': 4
    },
    
    # Poetry
    {
        'title': 'Leaves of Grass',
        'author': 'Walt Whitman',
        'isbn': '978-0-14-042199-5',
        'publisher': 'Penguin Classics',
        'publication_year': 1855,
        'pages': 720,
        'language': 'English',
        'genre': 'Poetry',
        'format': 'Paperback',
        'price': 16.99,
        'stock': 15,
        'description': 'Walt Whitman\'s groundbreaking collection of American poetry.',
        'delivery_date': 4
    },
    {
        'title': 'The Complete Poems of Emily Dickinson',
        'author': 'Emily Dickinson',
        'isbn': '978-0-316-18414-9',
        'publisher': 'Back Bay Books',
        'publication_year': 1890,
        'pages': 784,
        'language': 'English',
        'genre': 'Poetry',
        'format': 'Paperback',
        'price': 18.99,
        'stock': 12,
        'description': 'The complete collection of Emily Dickinson\'s innovative poetry.',
        'delivery_date': 4
    },
    {
        'title': 'The Sun and Her Flowers',
        'author': 'Rupi Kaur',
        'isbn': '978-1-4494-7908-0',
        'publisher': 'Andrews McMeel Publishing',
        'publication_year': 2017,
        'pages': 256,
        'language': 'English',
        'genre': 'Poetry',
        'format': 'Paperback',
        'price': 14.99,
        'stock': 25,
        'description': 'A collection of poetry about growth, healing, ancestry, and honoring one\'s roots.',
        'delivery_date': 2
    },
    
    # Classics
    {
        'title': 'The Divine Comedy',
        'author': 'Dante Alighieri',
        'isbn': '978-0-14-044475-9',
        'publisher': 'Penguin Classics',
        'publication_year': 1320,
        'pages': 798,
        'language': 'English',
        'genre': 'Classics',
        'format': 'Paperback',
        'price': 19.99,
        'stock': 15,
        'description': 'Dante\'s epic journey through Hell, Purgatory, and Paradise.',
        'delivery_date': 5
    },
    {
        'title': 'Don Quixote',
        'author': 'Miguel de Cervantes',
        'isbn': '978-0-06-093434-9',
        'publisher': 'HarperCollins',
        'publication_year': 1605,
        'pages': 940,
        'language': 'English',
        'genre': 'Classics',
        'format': 'Paperback',
        'price': 21.99,
        'stock': 18,
        'description': 'The adventures of an idealistic knight and his practical squire.',
        'delivery_date': 5
    },
    {
        'title': 'Les Misérables',
        'author': 'Victor Hugo',
        'isbn': '978-0-14-044430-8',
        'publisher': 'Penguin Classics',
        'publication_year': 1862,
        'pages': 1463,
        'language': 'English',
        'genre': 'Classics',
        'format': 'Paperback',
        'price': 24.99,
        'stock': 12,
        'description': 'An epic tale of justice, love, and redemption in 19th-century France.',
        'delivery_date': 6
    },
    {
        'title': 'War and Peace',
        'author': 'Leo Tolstoy',
        'isbn': '978-0-14-044793-4',
        'publisher': 'Penguin Classics',
        'publication_year': 1869,
        'pages': 1392,
        'language': 'English',
        'genre': 'Classics',
        'format': 'Paperback',
        'price': 23.99,
        'stock': 14,
        'description': 'Tolstoy\'s epic novel of Russian society during the Napoleonic era.',
        'delivery_date': 6
    },
    {
        'title': 'Anna Karenina',
        'author': 'Leo Tolstoy',
        'isbn': '978-0-14-303500-8',
        'publisher': 'Penguin Classics',
        'publication_year': 1877,
        'pages': 964,
        'language': 'English',
        'genre': 'Classics',
        'format': 'Paperback',
        'price': 20.99,
        'stock': 16,
        'description': 'A complex tale of love, society, and morality in imperial Russia.',
        'delivery_date': 5
    },
    
    # Adventure
    {
        'title': 'Treasure Island',
        'author': 'Robert Louis Stevenson',
        'isbn': '978-0-14-062034-4',
        'publisher': 'Penguin Classics',
        'publication_year': 1883,
        'pages': 240,
        'language': 'English',
        'genre': 'Adventure',
        'format': 'Paperback',
        'price': 11.99,
        'stock': 25,
        'description': 'A young boy\'s adventure with pirates in search of buried treasure.',
        'delivery_date': 3
    },
    {
        'title': 'Robinson Crusoe',
        'author': 'Daniel Defoe',
        'isbn': '978-0-14-043474-2',
        'publisher': 'Penguin Classics',
        'publication_year': 1719,
        'pages': 320,
        'language': 'English',
        'genre': 'Adventure',
        'format': 'Paperback',
        'price': 12.99,
        'stock': 20,
        'description': 'The survival story of a man stranded on a desert island.',
        'delivery_date': 3
    },
    {
        'title': 'The Adventures of Tom Sawyer',
        'author': 'Mark Twain',
        'isbn': '978-0-14-303999-0',
        'publisher': 'Penguin Classics',
        'publication_year': 1876,
        'pages': 274,
        'language': 'English',
        'genre': 'Adventure',
        'format': 'Paperback',
        'price': 11.99,
        'stock': 28,
        'description': 'The mischievous adventures of a boy growing up along the Mississippi River.',
        'delivery_date': 3
    },
    {
        'title': 'Into the Wild',
        'author': 'Jon Krakauer',
        'isbn': '978-0-385-48680-4',
        'publisher': 'Anchor',
        'publication_year': 1996,
        'pages': 207,
        'language': 'English',
        'genre': 'Adventure',
        'format': 'Paperback',
        'price': 14.99,
        'stock': 30,
        'description': 'The true story of Christopher McCandless\'s journey into the Alaskan wilderness.',
        'delivery_date': 3
    },
    
    # Contemporary Fiction
    {
        'title': 'The Kite Runner',
        'author': 'Khaled Hosseini',
        'isbn': '978-1-59448-000-3',
        'publisher': 'Riverhead Books',
        'publication_year': 2003,
        'pages': 371,
        'language': 'English',
        'genre': 'Contemporary Fiction',
        'format': 'Paperback',
        'price': 15.99,
        'stock': 32,
        'description': 'A powerful story of friendship, guilt, and redemption set in Afghanistan.',
        'delivery_date': 3
    },
    {
        'title': 'Life of Pi',
        'author': 'Yann Martel',
        'isbn': '978-0-15-602732-3',
        'publisher': 'Harcourt',
        'publication_year': 2001,
        'pages': 319,
        'language': 'English',
        'genre': 'Contemporary Fiction',
        'format': 'Paperback',
        'price': 14.99,
        'stock': 28,
        'description': 'A boy survives 227 days stranded on a lifeboat with a Bengal tiger.',
        'delivery_date': 3
    },
    {
        'title': 'The Alchemist',
        'author': 'Paulo Coelho',
        'isbn': '978-0-06-231500-7',
        'publisher': 'HarperOne',
        'publication_year': 1988,
        'pages': 163,
        'language': 'English',
        'genre': 'Contemporary Fiction',
        'format': 'Paperback',
        'price': 13.99,
        'stock': 40,
        'description': 'A philosophical novel about a shepherd\'s journey to find his personal legend.',
        'delivery_date': 2
    },
    {
        'title': 'The Time Traveler\'s Wife',
        'author': 'Audrey Niffenegger',
        'isbn': '978-0-15-602943-3',
        'publisher': 'Harcourt',
        'publication_year': 2003,
        'pages': 518,
        'language': 'English',
        'genre': 'Contemporary Fiction',
        'format': 'Paperback',
        'price': 16.99,
        'stock': 25,
        'description': 'A love story complicated by the husband\'s genetic disorder that causes time travel.',
        'delivery_date': 4
    },    {
        'title': 'Where the Crawdads Sing',
        'author': 'Delia Owens',
        'isbn': '978-0-7352-1909-0',
        'publisher': 'G.P. Putnam\'s Sons',
        'publication_year': 2018,
        'pages': 370,
        'language': 'English',
        'genre': 'Contemporary Fiction',
        'format': 'Paperback',
        'price': 16.99,
        'stock': 35,
        'description': 'A mystery and coming-of-age story set in the marshlands of North Carolina.',
        'delivery_date': 2
    },
    {
        'title': 'The Seven Husbands of Evelyn Hugo',
        'author': 'Taylor Jenkins Reid',
        'isbn': '978-1-5011-3981-2',
        'publisher': 'Atria Books',
        'publication_year': 2017,
        'pages': 400,
        'language': 'English',
        'genre': 'Contemporary Fiction',
        'format': 'Paperback',
        'price': 16.99,
        'stock': 30,
        'description': 'A reclusive Hollywood icon reveals her secrets to an unknown journalist.',
        'delivery_date': 3
    },
    {
        'title': 'Circe',
        'author': 'Madeline Miller',
        'isbn': '978-0-316-55633-4',
        'publisher': 'Little, Brown and Company',
        'publication_year': 2018,
        'pages': 393,
        'language': 'English',
        'genre': 'Fantasy',
        'format': 'Hardcover',
        'price': 19.99,
        'stock': 25,
        'description': 'A stunning reimagining of the Greek goddess Circe and her transformation from nymph to witch.',
        'delivery_date': 4
    },    {
        'title': 'Klara and the Sun',
        'author': 'Kazuo Ishiguro',
        'isbn': '978-0-571-36488-6',
        'publisher': 'Faber & Faber',
        'publication_year': 2021,
        'pages': 303,
        'language': 'English',
        'genre': 'Science Fiction',
        'format': 'Hardcover',
        'price': 24.99,
        'stock': 22,
        'description': 'A moving tale told from the perspective of an artificial friend observing human nature.',
        'delivery_date': 3
    },
    {
        'title': 'The Handmaid\'s Tale',
        'author': 'Margaret Atwood',
        'isbn': '978-0-385-49081-8',
        'publisher': 'Anchor Books',
        'publication_year': 1985,
        'pages': 311,
        'language': 'English',
        'genre': 'Science Fiction',
        'format': 'Paperback',
        'price': 15.99,
        'stock': 28,
        'description': 'A dystopian novel about a totalitarian society where women are subjugated.',
        'delivery_date': 3    },
    {
        'title': 'The Seven Moons of Maali Almeida',
        'author': 'Shehan Karunatilaka',
        'isbn': '978-1-64129-421-6',
        'publisher': 'The New Press',
        'publication_year': 2022,
        'pages': 416,
        'language': 'English',
        'genre': 'Contemporary Fiction',
        'format': 'Paperback',
        'price': 17.99,
        'stock': 24,
        'description': 'A darkly comic fantasy about a photographer navigating the afterlife in war-torn Sri Lanka.',
        'delivery_date': 3
    },
    {
        'title': 'Where Are You Going, Bernadette',
        'author': 'Maria Semple',
        'isbn': '978-0-316-20427-0',
        'publisher': 'Little, Brown and Company',
        'publication_year': 2012,
        'pages': 352,
        'language': 'English',
        'genre': 'Contemporary Fiction',
        'format': 'Paperback',
        'price': 15.99,
        'stock': 25,
        'description': 'A satirical novel about a brilliant architect who goes missing.',
        'delivery_date': 3
    },
    {
        'title': 'The Midnight Library',
        'author': 'Matt Haig',
        'isbn': '978-0-525-55947-4',
        'publisher': 'Viking',
        'publication_year': 2020,
        'pages': 288,
        'language': 'English',
        'genre': 'Contemporary Fiction',
        'format': 'Hardcover',
        'price': 18.99,
        'stock': 30,
        'description': 'A thought-provoking tale about life\'s infinite possibilities.',
        'delivery_date': 2
    },
    {
        'title': 'The Power',
        'author': 'Naomi Alderman',
        'isbn': '978-0-316-54730-1',
        'publisher': 'Little, Brown and Company',
        'publication_year': 2016,
        'pages': 341,
        'language': 'English',
        'genre': 'Science Fiction',
        'format': 'Paperback',
        'price': 17.99,
        'stock': 24,
        'description': 'A speculative fiction novel about women developing electrical powers.',
        'delivery_date': 3
    },
    {
        'title': 'Project Hail Mary',
        'author': 'Andy Weir',
        'isbn': '978-0-593-13520-0',
        'publisher': 'Ballantine Books',
        'publication_year': 2021,
        'pages': 496,
        'language': 'English',
        'genre': 'Science Fiction',
        'format': 'Hardcover',
        'price': 23.99,
        'stock': 26,
        'description': 'A science fiction novel about humanity\'s last hope for survival.',
        'delivery_date': 4
    },
    {
        'title': 'The Thursday Murder Club',
        'author': 'Richard Osman',
        'isbn': '978-1-984-88021-5',
        'publisher': 'Pamela Dorman Books',
        'publication_year': 2020,
        'pages': 368,
        'language': 'English',
        'genre': 'Mystery',
        'format': 'Paperback',
        'price': 16.99,
        'stock': 35,
        'description': 'Four retirees meet weekly to investigate cold cases.',
        'delivery_date': 2
    },
    {
        'title': 'Normal People',
        'author': 'Sally Rooney',
        'isbn': '978-1-984-82218-4',
        'publisher': 'Hogarth',
        'publication_year': 2018,
        'pages': 273,
        'language': 'English',
        'genre': 'Contemporary Fiction',
        'format': 'Paperback',
        'price': 16.99,
        'stock': 28,
        'description': 'A complex love story between two Irish teenagers.',
        'delivery_date': 3
    },
    {
        'title': 'The Guest List',
        'author': 'Lucy Foley',
        'isbn': '978-0-06-286841-5',
        'publisher': 'William Morrow',
        'publication_year': 2020,
        'pages': 320,
        'language': 'English',
        'genre': 'Thriller',
        'format': 'Paperback',
        'price': 15.99,
        'stock': 30,        'description': 'A wedding on a remote island turns deadly.',
        'delivery_date': 2
    },
    {
        'title': 'The Invisible Life of Addie LaRue',
        'author': 'V.E. Schwab',
        'isbn': '978-0-7653-9104-2',
        'publisher': 'Tor Books',
        'publication_year': 2020,
        'pages': 448,
        'language': 'English',
        'genre': 'Fantasy',
        'format': 'Hardcover',
        'price': 21.99,
        'stock': 28,
        'description': 'A young woman makes a Faustian bargain to live forever but is cursed to be forgotten.',
        'delivery_date': 3
    },
    {
        'title': 'The Invisible Bridge',
        'author': 'Julie Orringer',
        'isbn': '978-0-375-41435-8',
        'publisher': 'Knopf',
        'publication_year': 2010,
        'pages': 602,
        'language': 'English',
        'genre': 'Historical Fiction',
        'format': 'Paperback',
        'price': 18.99,
        'stock': 20,
        'description': 'A sweeping historical novel set during World War II.',
        'delivery_date': 4
    },
    {
        'title': 'The Song of Achilles',
        'author': 'Madeline Miller',
        'isbn': '978-0-06-213425-1',
        'publisher': 'Ecco',
        'publication_year': 2011,
        'pages': 416,
        'language': 'English',
        'genre': 'Historical Fiction',
        'format': 'Paperback',
        'price': 16.99,
        'stock': 32,
        'description': 'A retelling of the Trojan War through the relationship between Achilles and Patroclus.',
        'delivery_date': 3
    },
    {
        'title': 'Big Little Lies',
        'author': 'Liane Moriarty',
        'isbn': '978-0-399-16743-6',
        'publisher': 'G.P. Putnam\'s Sons',
        'publication_year': 2014,
        'pages': 460,
        'language': 'English',
        'genre': 'Contemporary Fiction',
        'format': 'Paperback',
        'price': 16.99,
        'stock': 28,
        'description': 'A darkly comic novel about three mothers whose lives unravel.',
        'delivery_date': 3
    },
    {
        'title': 'The Poppy War',
        'author': 'R.F. Kuang',
        'isbn': '978-0-06-266268-4',
        'publisher': 'Harper Voyager',
        'publication_year': 2018,
        'pages': 544,
        'language': 'English',
        'genre': 'Fantasy',
        'format': 'Paperback',
        'price': 18.99,
        'stock': 22,
        'description': 'A grimdark military fantasy inspired by 20th-century China.',
        'delivery_date': 4
    },
    {
        'title': 'The Vanishing Half',
        'author': 'Brit Bennett',
        'isbn': '978-0-525-53629-2',
        'publisher': 'Riverhead Books',
        'publication_year': 2020,
        'pages': 343,
        'language': 'English',
        'genre': 'Contemporary Fiction',
        'format': 'Hardcover',
        'price': 19.99,
        'stock': 30,
        'description': 'A multi-generational saga about identity, family, and race.',
        'delivery_date': 3
    },
    {
        'title': 'Such a Fun Age',
        'author': 'Kiley Reid',
        'isbn': '978-0-525-54118-0',
        'publisher': 'G.P. Putnam\'s Sons',
        'publication_year': 2019,
        'pages': 310,
        'language': 'English',
        'genre': 'Contemporary Fiction',
        'format': 'Paperback',
        'price': 16.99,
        'stock': 26,
        'description': 'A sharp social commentary about race and privilege.',
        'delivery_date': 3
    },
    {
        'title': 'Anxious People',
        'author': 'Fredrik Backman',
        'isbn': '978-1-5011-6078-6',
        'publisher': 'Atria Books',
        'publication_year': 2020,
        'pages': 352,
        'language': 'English',
        'genre': 'Contemporary Fiction',
        'format': 'Paperback',
        'price': 16.99,
        'stock': 32,
        'description': 'A heartwarming story about a failed bank robbery and the hostages.',
        'delivery_date': 2
    }
]

def add_sample_books():
    with app.app_context():
        # Clear existing books
        try:
            db.session.query(Book).delete()
            db.session.commit()
            
            for book_data in sample_books:
                book = Book(**book_data)
                db.session.add(book)
            
            db.session.commit()
            print(f"Added {len(sample_books)} sample books to the database!")
        except Exception as e:
            print(f"Error adding books: {e}")
            db.session.rollback()

if __name__ == '__main__':
    add_sample_books()